/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "mt_nanopb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(User, User, AUTO)
PB_BIND(Position, Position, AUTO)
PB_BIND(NodeInfo, NodeInfo, AUTO)
PB_BIND(MyNodeInfo, MyNodeInfo, AUTO)
PB_BIND(FromRadio, FromRadio, AUTO)
PB_BIND(ToRadio, ToRadio, 2)
